import os

MAIL_SERVER = "mail.smtp2go.com"
MAIL_PORT = 2525
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_DEBUG = True

MAIL_USERNAME = os.getenv("SMTP2GO_USER")
MAIL_PASSWORD = os.getenv("SMTP2GO_PASS")

MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER")

CONTACT_EMAIL = os.getenv("CONTACT_EMAIL")